[package]
name = "cargo-bsize"
version = "0.0.2"
authors = ["Boshen <boshenc@gmail.com>"]
categories = ["development-tools::cargo-plugins"]
edition = "2024"
include = ["/src", "/LICENSE", "/README.md"]
keywords = ["cargo", "binary-size", "bloat", "size", "optimization"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/boshen/cargo-bsize"
description = "Analyze Rust binary size and propose size-reducing changes"

[lints.rust]
absolute_paths_not_starting_with_crate = "warn"
non_ascii_idents = "warn"
unit-bindings = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)', 'cfg(coverage_nightly)'] }

[lints.clippy]
all = { level = "warn", priority = -1 }
# restriction
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
print_stdout = "warn" # Must be opt-in
print_stderr = "warn" # Must be opt-in
allow_attributes = "warn"
# I like the explicitness of this rule as it removes confusion around `clone`.
# This increases readability, avoids `clone` mindlessly and heap allocating by accident.
clone_on_ref_ptr = "warn"
disallowed_types = "warn"
# These two are mutually exclusive, I like `mod.rs` files for better fuzzy searches on module entries.
self_named_module_files = "warn" # "-Wclippy::mod_module_files"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
filetype_is_file = "warn"
get_unwrap = "warn"
impl_trait_in_params = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
rest_pat_in_fully_bound_structs = "warn"
unnecessary_safety_comment = "warn"
undocumented_unsafe_blocks = "warn"
infinite_loop = "warn"

[[bin]]
name = "cargo-bsize"
path = "src/main.rs"
test = false

[dependencies]
anyhow = "1.0.104"
bpaf = { version = "0.9.26", features = ["derive", "batteries"] }
cargo_metadata = "0.23.1"
gimli = { version = "0.34.0", default-features = false, features = ["read", "std"] }
object = { version = "0.40.0", default-features = false, features = ["read", "std"] }
rustc-demangle = "0.1.28"
rustc-hash = "2.1.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.release]
# Configurations explicitly listed here for clarity.
# Using the best options for performance.
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols" # set to `false` for debug information
debug = false # set to `true` for debug information
panic = "abort" # Let it crash and force ourselves to write safe Rust.

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false
